# Generated by Django 4.0.1 on 2022-01-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Expert', 'Expert')], default='Yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=200, null=True),
        ),
    ]
